---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 150 words! -->

Interstitial lung diseases (ILDs) are debilitating disorders that cause patients to slowly lose their lung function, resulting in shortness of breath, limited capacity for movement, and subsequent death. Over 4,000 British Columbians currently suffer from some form of ILD, yet not all of them receive proper therapy due to difficulties in identifying the precise ILD subtype. Unfortunately, diagnosing ILDs is difficult due to frequently nonspecific test results – patients currently experience up to a 55% rate of misdiagnosis. Even when patients are correctly diagnosed, certain patients experience a rapid decline in lung function and little is known regarding the biological mechanisms behind this phenotype. To address the need for better ILD biomarkers, the goal of this thesis was to identify molecular markers in blood samples of ILD that are able to accurately identify specific subtypes and predict disease stability or progression.  