---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This section is optional -->

In 2015, I was freshly graduated from my MSc and looking for a job. While I had 'wet lab' experience, my research interests shifted towards data science ('dry lab') after a night of analyzing player usage from my favourite hockey team exposed a strategic flaw that eventually made it into a [local hockey blog](https://web.archive.org/web/20150805160802/http://canucksarmy.com/2015/4/17/looks-like-the-canucks-are-just-rolling-their-lines-1-2-3-fore) and, eventually, national news. Thankfully, my friend Duncan MacGillivray introduced me to his supervisor, Dr. Tobias Kollmann, who took a chance and hired me to process blood samples for the CHILD study and gave me an orphan project that required high dimensional data analysis. This forced me to learn how to use R and inspired me to pursue a PhD focusing on data analysis. Through Dr. Kollmann, I was introduced to my primary supervisor, Dr. Scott J. Tebbutt, who suggested a thesis centred around ILD after a chance conversation with Dr. Christopher J. Ryerson, my co-supervisor. 

Dr. Tebbutt has been a fantastic mentor and supported all of my intellectual pursuits, but he has also instilled a sense of community in my role as a scientist, having encouraged me to create a trainee association at the Centre for Heart Lung Innovation (HLI). I am continually amazed and inspired by Dr. Ryerson's knowledge of ILDs, and he has been excellent in guiding me with his clinical expertise in becoming a translational researcher. I would also like to acknowledge Dr. Sabina Guler and Dr. Boyang Zheng for their clinical knowledge as respirologists, which has been invaluable in completing our projects.

I have enormous gratitude for patients with ILD. They have been extremely generous in providing samples for research and brave for attending appointments in-person at the Pacific Lung Health Centre amidst a pandemic. Their contributions have been invaluable in uncovering mechanisms of ILD and opening new avenues of research in the hopes of finding a cure.

Over the course of my graduate studies, I have been affiliated with the Prevention of Organ Failure (PROOF) Centre of Excellence in order to learn about biomarker discovery. Much of my analytical knowledge can be credited to my time here, and in particular I would like to thank Casey P. Shannon for his guidance. I also am grateful to the numerous staff members of PROOF and Tebbutt lab members over the years, including but not limited to Sara Assadian, Paloma Stanar Burns, Dr. Zsuzsanna Hollander, Dr. Bruce McManus, and Paula Piper. All of my data extraction was performed at the molecular phenotyping core at HLI, and I am thankful for the core staff, Basak Sahin and Beth Whalen, for their assistance when I ran out of reagents and their tolerance of my fairly poor lab habits early on in my studies. 

Funding for my PhD was primarily provided by a Doctoral Research Award from the Canadian Institutes of Health Research (CIHR), but my application nearly did not happen without the persistence of Dr. Mina Park and Dr. Ganive Bhinder in forcing me to apply. While I was unsuccessful in my first attempt, the feedback helped me strengthen my successful application in the next year. I would also like to thank MITACS for supporting my salary for the remainder of my studies, as well as the BC Lung Association and GenomeBC for approving my research grants to support the work performed in Chapter 3, 4, and 5. 

My skills as a science communicator continue to be a work in progress, but I credit Dr. Tebbutt for encouraging me to try unconventional speaking methods. While my early attempts were far from perfect, over time, I eventually received recognition for my efforts at local conferences, and was invited to present at the UBC Respiratory Rounds and the 2022 International Colloquium on Lung and Airway Fibrosis. Much of this was due to the participation in UBC's 3-minute thesis competition, where I was a finalist in 2020. This experience allowed me to hone the balance of delivering an effective message with relatable analogies, and would not have been possible without an "I'll do it if you do it" pact with a friend, with whom I would also go on to develop the UBC Science Communication event funded by the UBC Faculty of Medicine. 

In 2022, as the world was reopening with the introduction of COVID-19 vaccines, I applied for and was awarded funding from CIHR's Michael Smith Foreign Study Supplement, which allowed me to study biclustering with Dr. Jan Baumbach and Dr. Olga Zolotareva at the University of Hamburg. This visit was a transformational for me as a scientist; I learned a new analytical method and was challenged in my coding ability. It is an experience I will never forget, and I am grateful for their hospitality.

In addition to the intellectual challenges, PhDs can also be emotionally taxing. I deeply appreciate Dr. Sumin Na and Douglas Wong for their willingness to listen to my endless complaints. And finally, there are not many parents who would support 15 years of schooling, but apparently I lucked out. 