---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This section is mandatory! -->

The objective of this thesis was to identify ILD blood for novel diagnostic and prognostic molecular biomarkers. A comprehensive systematic review and meta-analysis was performed to illustrate the ILD transcriptomics landscape. We identified classification models differentiating between ILD subtypes that highlighted shared and unique molecular pathways in ILD, in addition to subtype-agnostic molecular endotypes in the lung. The SSc-ILD peripheral transcriptome was the most molecularly distinct ILD subtype, showing a distinct interferon signature in addition to genes associated with PPF, in the first between-subtype comparison of ILD subtypes at the transcriptomics level. A model based on gene expression data was also developed and validated to predict transplant-free survival in ILD patients. Finally, we show the first scRNA-seq comparison between PBMC samples taken from patients with IPF and HP, and identified cell-specific genes associated with each subtype in monocytes and NK cells. 

Clinical management of ILDs continues to be a topic of interest within the field. At the beginning of my PhD studies, identifying IPF from other ILD subtypes was a key clinical question given the approval of pirfenidone in 2012 (Esbriet\textregistered) and nintedanib in 2015 (Ofev\textregistered) as approved therapies for IPF in place of immunosuppressive therapuetics, which were shown to be harmful. Since then, progressive pulmonary fibrosis has become a topic of discussion given the efficacy of nintedanib in non-IPF ILD subtypes that show a rapid progression, and this was incorporated into patient selection for the RNA-seq study described in Chapter 4. While I was unable to identify differentially expressed genes between IPF and HP, a common diagnostic dilemma, single-cell profiling of both subtypes revealed cell-specific differences in transcriptomics. Although relevant diagnostic biomarkers were difficult to observe at the bulk transcriptomics level, transplant-free survival appeared to be associated with specific genes in all ILD subtypes, and this finding may have more clinical utility in providing decision makers with rationale to commence anti-fibrotic therapy along with other interventions. 

Timing is also a key consideration for research into ILD biomarkers, both at the micro- and macro-level. The COVID-19 pandemic was difficult to overcome due to workplace outbreaks at both the clinic and sequencing facilities, and difficulties in obtaining patient samples given their preference to conduct appointments virtually during a pandemic, particularly during variant waves. Despite care in selecting patients considered to be early in disease progression, it is difficult to determine the initiation of lung fibrosis, and molecular markers may change over time. Single cell RNA-sequencing is also a novel methodology that has yet to reach its apex in analytical power - since the beginning of the single cell study, three new versions of the software used to analyze scRNA-seq data have been released, and studies have shown that certain differential expression algorithms result in false positives. Novel cell-based biomarkers and technologies should be a priority in the immediate future. 

The work shown here is an extensive examination of the peripheral ILD transcriptome, and will hopefully provide a foundation for future research studies to expand on. 